import 'dart:convert';

import 'package:http/http.dart';

import 'newsModel.dart';

Future<Autogenerated> getdata() async {
  var res0 = await get(Uri.parse(
      "https://newsapi.org/v2/everything?q=trending&apiKey=db7c5e060c1c49188fe23e493eee3257"));
  if (res0.statusCode == 200) {
    var data0 = await Autogenerated.fromJson(jsonDecode(res0.body));
    return data0;
  } else {
    throw Exception("error");
  }
}
Future<Business>   getBnews()async{
  var res1 = await get(Uri.parse("https://newsapi.org/v2/everything?q=business&apiKey=db7c5e060c1c49188fe23e493eee3257"));
  if(res1.statusCode==200){
    var data1 = Business.fromJson(jsonDecode(res1.body));
    return data1;
  }
  else{
    throw Exception("error");
  }
}
Future<Sports> getsnews()async{
  var res2=await get(Uri.parse("https://newsapi.org/v2/everything?q=sports&apiKey=db7c5e060c1c49188fe23e493eee3257"));
  if(res2.statusCode==200){
    var data2 =Sports.fromJson(jsonDecode(res2.body));
    return data2;
  }
  else{
    throw Exception("error");
  }
}