import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter1/Apiintegration/userdetails.dart';
import 'package:http/http.dart';

class User_det extends StatefulWidget {
  const User_det({super.key});

  @override
  State<User_det> createState() => _User_detState();
}

class _User_detState extends State<User_det> {
  Future<Autogenerated> Showdet() async {
    var det = await get(Uri.parse("https://dummyjson.com/users"));
    var data = Autogenerated.fromJson(jsonDecode(det.body));
    return data;
    // if (det.statusCode == 200) {
    //   var data = Autogenerated.fromJson(jsonDecode(det.body));
    //   return data;
    //
    // } else {
    //   throw Exception("error");
    // }
    print(det.body);

  }

  // @override
  // void initState() {
  //   // TODO: implement initState
  //   super.initState();
  //   Showdet();
  // }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body:Center(child: ElevatedButton(onPressed: (){
        Showdet();
      },child: Text("")),)
      // FutureBuilder(
      //   builder: (context, AsyncSnapshot<Autogenerated> snapshot) {
      //     if (snapshot.connectionState == ConnectionState.waiting) {
      //       return Center(
      //         child: CircularProgressIndicator(),
      //       );
      //     } else if (snapshot.hasError) {
      //       return Center(
      //         child: Text("ERROR"),
      //       );
      //     } else if (!snapshot.hasData) {
      //       return Center(
      //         child: Text("NO DATA"),
      //       );
      //     } else if (snapshot.hasData) {
      //       List<Users>? User = snapshot.data?.users;
      //       ListView.separated(
      //           itemBuilder: (_, int index) {
      //             return Card(
      //               elevation: 3,
      //               child: Row(children: [
      //                 Image(
      //                     width: 40,
      //                     height: 50,
      //                     image: NetworkImage("${User[index].image}")),
      //                 Column(
      //                   children: [
      //                     Row(
      //                       children: [
      //                         Text("${User[index].firstName}"),
      //                         Text("${User[index].lastName}"),
      //                       ],
      //                     ),
      //                     Text("${User[index].address?.address}"),
      //                     Text("${User[index].address?.state}"),
      //                     Row(
      //                       children: [
      //                         Text("${User[index].birthDate}"),
      //                         Padding(
      //                           padding: const EdgeInsets.only(left: 50),
      //                           child: Text("${User[index].age}"),
      //                         ),
      //                       ],
      //                     ),
      //                   ],
      //                 )
      //               ]),
      //             );
      //           },
      //           separatorBuilder: (_, int index) {
      //             return Divider(
      //               height: 2,
      //             );
      //           },
      //           itemCount: User!.length);
      //     }
      //     else {
      //       return Text("error");
      //     }
      //     return Text("");
      //   },
      //   future: Showdet(),
      // ),
    );
  }
}
