import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:http/http.dart';

import 'MyModel3.dart';

class apI3 extends StatefulWidget {
  const apI3({super.key});

  @override
  State<apI3> createState() => _apI3State();
}

class _apI3State extends State<apI3> {

  Future<Autogenerated>  showdata()async{

    var det= await get(Uri.parse("https://jsonplaceholder.typicode.com/posts"));
    if(det.statusCode==200){
      var data =Autogenerated.fromJson(jsonDecode(det.body));
      return data;
    }else{
      throw Exception("ERROR");
    }
    print (det.body);
  }
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    showdata();
  }
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: FutureBuilder(future: showdata(), builder: (context,AsyncSnapshot<Autogenerated> snapshot){
        if(snapshot.connectionState==ConnectionState.waiting){
          return Center(child: CircularProgressIndicator(),);
        }
        else if(snapshot.hasError){
          return Center(child: Text("has error"),);
        }
        else if(!snapshot.hasData){
          return Center(child: Text("no data"),);
        }
        else if(snapshot.hasData){
          return Center(child: Text("OK"),);
        }
        else{
          return Center(child: Text("ERROR"),);
        }
      })
    );
  }
}

